export const ASSUMPTION_GROUPS = [
  {
    title: "Membership / Revenue",
    fields: [
      ["openingPrice", "Opening membership price", "currency"],
      ["foundingMembers", "Founding members at opening", "number"],
      ["foundingDiscount", "Founding member discount", "percent"],
      ["priceThreshold", "Member threshold for price increase", "number"],
      ["increasedPrice", "Increased membership price", "currency"],
      ["membershipPriceInflation", "Membership price inflation", "percent"],
      ["plateauMembers", "Member plateau", "number"],
      ["monthsToPlateau", "Months to plateau", "number"],
      ["growthCurve", "Member growth curve factor", "decimal"],
      ["attrition", "Monthly attrition", "percent"],
      ["additionalRevenuePct", "Additional revenue", "percent"],
      ["salesTax", "Sales tax", "percent"],
    ],
  },
  {
    title: "Class / Staffing",
    fields: [
      ["weekdaySlotsOpening", "Weekday time slots at opening", "number"],
      ["weekendSlotsOpening", "Weekend time slots at opening", "number"],
      ["trainersPerSlot", "Trainers needed per time slot", "number"],
      ["trainerWage", "Trainer wage per class", "currency"],
      ["laborInflation", "Labor inflation", "percent"],
      ["membersPerWeekdaySlot", "Members per added weekday slot", "number"],
      ["membersPerWeekendSlot", "Members per added weekend slot", "number"],
      ["managerThreshold", "Location manager threshold", "number"],
      ["managerSalary", "Location manager salary", "currency"],
      ["frontDeskHours", "Front desk hours before manager", "number"],
      ["frontDeskWage", "Front desk hourly wage", "currency"],
    ],
  },
  {
    title: "Rent / Operating Expenses",
    fields: [
      ["squareFeet", "Gym square footage", "number"],
      ["rentPsfMonthly", "Rent per square foot monthly", "currency"],
      ["freeRentMonths", "Rent-free months", "number"],
      ["annualRentIncrease", "Rent inflation", "percent"],
      ["royalties", "Royalties", "percent"],
      ["brandFund", "Brand fund", "percent"],
      ["techFee", "TYG tech fee", "percent"],
      ["minMarketing", "Minimum marketing spend", "currency"],
      ["marketingPct", "Marketing budget", "percent"],
      ["repairsPct", "Repairs", "percent"],
      ["waterElectric", "Water / electric", "currency"],
      ["cleaning", "Cleaning", "currency"],
      ["phoneInternet", "Phone / internet", "currency"],
      ["insurance", "Insurance", "currency"],
      ["accounting", "Accounting", "currency"],
      ["otherExpenses", "Other expenses", "currency"],
      ["generalExpensesInflation", "General expenses inflation", "percent"],
    ],
  },
  {
    title: "Initial Investment / Loan Terms",
    fields: [
      ["franchiseFee", "Franchise fee", "currency"],
      ["equipment", "Equipment", "currency"],
      ["construction", "Construction costs", "currency"],
      ["tenantImprovement", "Tenant improvement allowance", "currency"],
      ["preOpenMarketing", "Pre-open marketing", "currency"],
      ["legalFees", "Legal fees", "currency"],
      ["otherStartupCosts", "Other startup costs", "currency"],
      ["depositMonths", "Rental deposit months", "number"],
      ["loanTermYears", "Loan term", "number"],
      ["loanRate", "Loan rate", "percent"],
    ],
  },
];
