export const TINKER_ASSUMPTION_FIELDS = [
  ["foundingMembers", "Founding members", "number"],
  ["plateauMembers", "Member plateau", "number"],
  ["monthsToPlateau", "Months to plateau", "number"],
  ["growthCurve", "Growth curve factor", "decimal"],
  ["attrition", "Monthly attrition", "percent"],
  ["openingPrice", "Opening price", "currency"],
  ["increasedPrice", "Increased price", "currency"],
  ["foundingDiscount", "Founding discount", "percent"],
  ["additionalRevenuePct", "Add-on revenue", "percent"],
  ["weekdaySlotsOpening", "Weekday slots", "number"],
  ["weekendSlotsOpening", "Weekend slots", "number"],
  ["trainersPerSlot", "Trainers per slot", "number"],
  ["membersPerWeekdaySlot", "Members / weekday slot", "number"],
  ["membersPerWeekendSlot", "Members / weekend slot", "number"],
  ["marketingPct", "Marketing percent", "percent"],
  ["minMarketing", "Minimum marketing", "currency"],
];

export const ASSUMPTION_GROUPS = [
  {
    title: "Tinker / Scenario Drivers",
    description: "The assumptions you will adjust most often to test outcomes.",
    fields: TINKER_ASSUMPTION_FIELDS,
  },
  {
    title: "Stable Planning Assumptions",
    description: "Important defaults that should change less often.",
    fields: [
      ["priceThreshold", "Member threshold for price increase", "number"],
      ["membershipPriceInflation", "Membership price inflation", "percent"],
      ["salesTax", "Sales tax", "percent"],
      ["trainerWage", "Trainer wage per class", "currency"],
      ["laborInflation", "Labor inflation", "percent"],
      ["managerThreshold", "Location manager threshold", "number"],
      ["managerSalary", "Location manager salary", "currency"],
      ["frontDeskHours", "Front desk hours before manager", "number"],
      ["frontDeskWage", "Front desk hourly wage", "currency"],
      ["freeRentMonths", "Rent-free months", "number"],
      ["annualRentIncrease", "Rent inflation", "percent"],
      ["royalties", "Royalties", "percent"],
      ["brandFund", "Brand fund", "percent"],
      ["techFee", "TYG tech fee", "percent"],
      ["repairsPct", "Repairs", "percent"],
      ["waterElectric", "Water / electric", "currency"],
      ["cleaning", "Cleaning", "currency"],
      ["phoneInternet", "Phone / internet", "currency"],
      ["insurance", "Insurance", "currency"],
      ["accounting", "Accounting", "currency"],
      ["otherExpenses", "Other expenses", "currency"],
      ["generalExpensesInflation", "General expenses inflation", "percent"],
      ["loanTermYears", "Loan term", "number"],
      ["loanRate", "Loan rate", "percent"],
    ],
  },
  {
    title: "Current / Known Location Costs",
    description: "Static setup costs and facility facts for the signed locations.",
    fields: [
      ["squareFeet", "Gym square footage", "number"],
      ["rentPsfMonthly", "Rent per square foot monthly", "currency"],
      ["franchiseFee", "Franchise fee", "currency"],
      ["equipment", "Equipment", "currency"],
      ["construction", "Construction costs", "currency"],
      ["tenantImprovement", "Tenant improvement allowance", "currency"],
      ["preOpenMarketing", "Pre-open marketing", "currency"],
      ["legalFees", "Legal fees", "currency"],
      ["otherStartupCosts", "Other startup costs", "currency"],
      ["depositMonths", "Rental deposit months", "number"],
    ],
  },
];
